#!/usr/local/bin/ruby
# frozen_string_literal: true

require_relative 'lib/controller'
require_relative 'lib/input/parser'

controller = Controller.new(Input::Parser.new)
controller.introduce
result = controller.execute

result.each { |line| puts "#{line}\n" }
