#!/usr/local/bin/ruby
# typed: strict
# frozen_string_literal: true

require 'sorbet-runtime'

require_relative 'lib/controller'

controller = Controller.new
controller.introduce
result = controller.execute

result.each { |line| puts "#{line}\n" }
