name: validation
on:
  - push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: Prepare
        run: make provision
      - name: Lint
        run: make lint
      - name: Type-check
        run: make type-check
      - name: Test
        run: make test
